#!/bin/bash

# Copyright 2011 Boris Kogan (boris@thekogans.net)
#
# This file is part of thekogans_toolchain.
#
# thekogans_toolchain is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# thekogans_toolchain is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with thekogans_toolchain. If not, see <http://www.gnu.org/licenses/>.

if [ "$TOOLCHAIN_DEFAULT_SVC" == "svn" ]; then
    export TOOLCHAIN_SVN_URL=
elif [ "$TOOLCHAIN_DEFAULT_SVC" == "git" ]; then
    export TOOLCHAIN_GIT_URL=https://github.com/thekogans
    export TOOLCHAIN_GIT_RAW_URL=https://raw.github.com/thekogans
fi
