#!/bin/bash

# Copyright 2011 Boris Kogan (boris@thekogans.net)
#
# This file is part of thekogans_toolchain.
#
# thekogans_toolchain is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# thekogans_toolchain is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with thekogans_toolchain. If not, see <http://www.gnu.org/licenses/>.

# Visual Studio 2017 changes the directory structure supported by it's
# predecessors. This script will correctly point to the right bin directory.
# NOTE: If you want to do cross compilation (i386 -> x86_64 or x86_64 -> i386)
# you will need to change the TOOLCHAIN_VISUAL_STUDIO_DIR.

TOOLCHAIN_WINDOWS_SDK_DIR=`cygpath -au "$WindowsSdkVerBinPath"x86`
TOOLCHAIN_VISUAL_STUDIO_DIR=`cygpath -au "$VCToolsInstallDir"bin\\\Hostx86\\\x86`
TOOLCHAIN_DEFAULT_GENERATOR=vs2019

export TOOLCHAIN_WINDOWS_SDK_DIR \
       TOOLCHAIN_VISUAL_STUDIO_DIR \
       TOOLCHAIN_DEFAULT_GENERATOR
