#!/bin/bash

# Copyright 2011 Boris Kogan (boris@thekogans.net)
#
# This file is part of thekogans_toolchain.
#
# thekogans_toolchain is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# thekogans_toolchain is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with thekogans_toolchain. If not, see <http://www.gnu.org/licenses/>.

prefix=
default_environment=yes
thekogans_source=no

# Parse the command line.
for i in "$@"; do
    case $i in
        -p:*|--prefix:*)
            prefix="${i#*:}"
            ;;
        -de:*|--default-environment:*)
            default_environment="${i#*:}"
            ;;
        -ts:*|--thekogans-source:*)
            thekogans_source="${i#*:}"
            ;;
    esac
done

if [ "$prefix" == "" ]; then
    echo "usage: $0 \
[-p | --prefix]:path \
[[-de | --default-environment]:[yes | no]] \
[[-ts | --thekogans-source]:[yes | no]]"
    exit 1
else
    prefix="$(cd $prefix && pwd)"
fi

TOOLCHAIN_ROOT="$(cd $(dirname ${BASH_SOURCE[0]}) && pwd)"
. "$TOOLCHAIN_ROOT"/common/bin/setenvironment "$@"

REAL_TOOLCHAIN_ROOT="$prefix/$TOOLCHAIN_NAME"
if [ ! -d "$REAL_TOOLCHAIN_ROOT" ]; then
    mkdir -p "$REAL_TOOLCHAIN_ROOT"
    check_errors $?
fi

mkdir -p "$TOOLCHAIN_DIR"/bin "$TOOLCHAIN_DIR"/config
check_errors $?

cd "$TOOLCHAIN_ROOT"
check_errors $?

# thekogans_build_system
if [ -d thekogans_build_system ]; then
    cd thekogans_build_system
    check_errors $?
    if [ ! -f .thekogans_build_system_done ]; then
        "$TOOLCHAIN_SHELL" ./install
        check_errors $?
        touch .thekogans_build_system_done
        check_errors $?
    fi
    cd ..
    check_errors $?
fi

# Copy the new build system to the real toolchain.
for file in "$TOOLCHAIN_ROOT"/*; do
    if [ "$file" != "$TOOLCHAIN_ROOT"/bootstrap ] && \
            [ "$file" != "$TOOLCHAIN_ROOT"/drops ] && \
            [ "$file" != "$TOOLCHAIN_ROOT"/defaultenvironment ] && \
            [ "$file" != "$TOOLCHAIN_ROOT"/sources ] && \
            [ "$file" != "$TOOLCHAIN_ROOT"/Sources.xml ] && \
            [ "$file" != "$TOOLCHAIN_ROOT"/thekogans_build_system ]; then
        cp -v -r "$file" "$REAL_TOOLCHAIN_ROOT"
        check_errors $?
    fi
done

if [ "$default_environment" == "yes" ]; then
    DEVELOPMENT_ROOT="$prefix"
    TOOLCHAIN_ROOT="$REAL_TOOLCHAIN_ROOT"
    "$TOOLCHAIN_ROOT"/common/bin/setdefaultenvironment
fi

if [ "$thekogans_source" == "yes" ]; then
    "$TOOLCHAIN_SHELL" \
        "$TOOLCHAIN_ROOT"/common/bin/addsource \
        -o:thekogans \
        -u:https://raw.github.com/ch00ch00man/sources/master
fi

exit 0
