#!/bin/bash

# Copyright 2011 Boris Kogan (boris@thekogans.net)
#
# This file is part of thekogans_toolchain.
#
# thekogans_toolchain is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# thekogans_toolchain is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with thekogans_toolchain. If not, see <http://www.gnu.org/licenses/>.

TOOLCHAIN_PROGRAM_SUFFIX=
TOOLCHAIN_SHARED_LIBRARY_SUFFIX=so
TOOLCHAIN_STATIC_LIBRARY_SUFFIX=a

export TOOLCHAIN_PROGRAM_SUFFIX \
    TOOLCHAIN_SHARED_LIBRARY_SUFFIX \
    TOOLCHAIN_STATIC_LIBRARY_SUFFIX
